[2주차] 동아리 활동 일지 제출합니다.
2024-woowacourse-study/gae-mun-tam pull request #3
Opened 2024-05-31 00:59 UTC by 3Juhwan

슬랙에 작성한 내용에 조금 재구성하여 작성했습니다. 
- 토미와의 면담 내용은 별도로 작성하는 것이 좋을 것 같아서 포함하지 않았습니다. 
- 개인의 경험이 다수 포함되어 있어 다소 민감할 수 있을 것 같습니다. 검토하고 수정 요청 부탁드립니다.

2024-05-31 05:25 UTC, le2sky requested changes
👍👍👍 고생하셨습니다. 사소한 피드백 남겼는데, 살펴봐주세요.

2024-05-31 05:25 UTC, le2sky commented on log/week2.md
> +**아톰**
```suggestion
**아톰의 경험**
```

2024-05-31 05:25 UTC, le2sky commented on log/week2.md
> +    - 장점1: 코드 리뷰 후에 머지되는 프로세스를 통해 결국 동기적으로 진행되는데, 어느정도 해결할 수 있다.
동기적으로 진행되는 방식에서 오는 단점도 추가해주면 어떨까요?
예를 들어, '피로감', '인적 자원 효율적으로 사용하지 못함', '귀찮다는 사유로 코드 리뷰를 대충 진행함' 정도 있을 것 같아요.

2024-06-02 15:56 UTC, GIVEN53 approved these changes
간결하고 군더더기 없네요 
개인의 경험도 잘 추상화해서 작성했다고 생각해요 👍🏻

2024-06-04 01:44 UTC, le2sky approved these changes

2024-06-04 01:45 UTC, alstn113 commented
잘 정리됐네요 굳!

2024-06-04 05:56 UTC, alstn113 approved these changes

2024-06-04 05:57 UTC, merged