[레벨 2 방학] 동아리 활동 일지 제출합니다.
2024-woowacourse-study/gae-mun-tam pull request #5
Opened 2024-06-28 09:05 UTC by le2sky

레벨 2 방학 활동 일지를 제출합니다. 간략하게 적어봤어요. 추가 내용 필요하다면 피드백 부탁드립니다!

2024-06-28 09:08 UTC, le2sky commented
파일명이나 PR이 n주차로 고정되어 있었는데요. 이 부분 개선이 필요할까요?
n주차는 시작일을 알아야하는 문제점이랑 n이 연속되지 않는게 불편할수도 있어서요.
n회차가 제일 적당해 보이긴 하네요.

2024-06-28 09:09 UTC, le2sky commented
추가로 토미랑 리사와 면담했던 내용도 로그로 남겨야하는지 의견 궁금해용

2024-06-28 10:52 UTC, alstn113 requested changes
내용에 있는 N주차 대신에 N회차가 좋을 것 같아요.
그리고 파일 명을 week1.md 대신에 회의했던 날짜와 회차를 알 수 있게 2024-06-28-[001].md는 어떨까요?
ex) YYYY-MM-DD-[00N].md

2024-06-28 10:52 UTC, alstn113 commented on log/level2-vacation.md
> +- 소프트웨어 장인 정신을 읽고 서로 이야기를 나눔
```txt
현대 소프트웨어 개발자의 역할에 대해 배우고, 애자일 방법론과 테스트의 중요성을 이해했습니다.
소프트웨어 장인이 되기 위한 태도와 책임감을 익히고, 내 커리어의 주인이 누구인지 고민해 보았습니다. 
또한, 무조건적인 '네' 대신 '아니오'라고 말하고 대안을 제시하는 법의 중요성도 배웠습니다.
```

이런 내용을 추가하는건 어떨까요? 너무 내용이 없어서 심심해요.

2024-06-28 10:53 UTC, alstn113 commented on log/level2-vacation.md
> +- 소프트웨어 장인 정신을 읽고 서로 이야기를 나눔
아 그리고 토미, 리사 슬랙에 적은 거 그대로 추가해도 괜찮지 않을까요?

2024-06-28 13:44 UTC, GIVEN53 approved these changes
구름의 코멘트 내용을 추가하면 더욱 풍부할 것 같아요!
토미, 리사 면담내용은 다른 디렉토리 하위에서 작성하는 것도 좋을 듯 해요

저도 YYYY-MM-DD-[00N].md 파일명 좋아요
PR도 아톰 의견과 같이 [N회차]가 적당해 보여요
망쵸 의견까지 추합해서 이전 md 파일명도 함께 수정해서 머지해주시면 감사하겠습니다 😊

2024-06-29 16:49 UTC, 3Juhwan approved these changes
조금 늦었네요 😢 잘 작성해 주셨고, 고생하셨습니다 :)
수정하면 좋을 것 같은 부분, 남겨두었어요. 정말 사소해서, 반영은 선택입니다! 

세 분이 파일명에 대해 토의해 주셨네요. 제 의견은 `YYYY-MM-DD.md`형식입니다! 
- 위 형식으로 하면 항상 정렬됨이 보장될 것 같아요. 
- 회차가 중요한 정보인지에 대해 의문이 들었고, 너무 길어지는 것 같아서 누락했어요. 이것이 중요한 정보라면 저에게 공감대 형성을 부탁드립니다 😀 
- PR 제목 또는 글 제목에 회차 정보를 기재하는 것이 좀 더 의미가 있다고 생각해요!

2024-06-29 16:49 UTC, 3Juhwan commented on log/level2-vacation.md
> +- 회의는 온/오프라인(주말에 잠실)
```suggestion
- 주간 팀 내 있었던 일 공유
- 한 명이 대화 안건을 갖고 와서 토의하기 (ex. 질문 잘하는 방법)
- 활동은 온/오프라인(주말, 잠실)
```

2024-07-01 13:37 UTC, le2sky commented on log/level2-vacation.md
> +- 회의는 온/오프라인(주말에 잠실)
확실히 추상적이긴 하네요. 이 부분은 레벨 3때 책 스터디를 하자라는 의미로 작성됐어요.
현재는 정확하게 작성하려고 노력했습니다. 여전히 불필요한 내용이라고 생각이 드시면 편히 말씀 주세용 👍

2024-07-01 13:40 UTC, le2sky commented
파일명 형식에 대해서 의견이 다른 부분이 있네요. 우선은 망쵸 제안대로 변경했어요.
개인적으로는 정렬만 잘되면 무엇이든지 괜찮다는 의견이라서요. 그나마 망쵸의 제안해준게 짧아서 yyyy-mm-dd 형식으로 변경했습니다.
어색하거나 추가 의견 있으시다면 자유롭게 커멘트 남겨주세용 😀

2024-07-01 13:41 UTC, alstn113 commented
좋아용

2024-07-01 13:42 UTC, alstn113 approved these changes

2024-07-01 13:42 UTC, le2sky commented on log/level2-vacation.md
> +- 소프트웨어 장인 정신을 읽고 서로 이야기를 나눔
굳굳 좋아용 👍
현재 PR에서는 다루지 않고, 새로운 PR 열어서 하는게 나을 것 같아요.

2024-07-01 13:44 UTC, GIVEN53 approved these changes
굿 👍🏻 고생했어요!

2024-07-01 14:22 UTC, 3Juhwan requested changes
좋습니다 👍

2024-07-01 14:22 UTC, 3Juhwan commented on log/2024-05-16.md
> +### 개발 문화 탐구 동동 1화차 일지
```suggestion
### 개발 문화 탐구 동동 1회차 일지
```

2024-07-01 14:24 UTC, 3Juhwan approved these changes

2024-07-01 14:24 UTC, merged