[코치와의 인터뷰 1회차] 인터뷰 면담 일지 제출합니다.
2024-woowacourse-study/gae-mun-tam pull request #6
Opened 2024-07-04 10:07 UTC by le2sky

아톰입니다. 코치분의 요구사항으로 닉네임을 제외한 기록을 제출합니다.
PR 헤더의 경우에는 임의로 작성해봤는데요.  수정이 필요하다면 의견 공유 부탁드립니다.
그리고 전체적으로 어색한 부분이 있거나, 추가적으로 필요한 부분이 있다면 자유롭게 의견 남겨주시면 좋을 것 같아요.

++ 다른 코치 분의 인터뷰는 망쵸가 작성한다고 연락왔습니다.

2024-07-04 12:27 UTC, alstn113 requested changes
아톰 정리해주셔서 감사합니다. 👍 

아톰이 프로젝트 회의에서 말했던 말들과 코치와의 인터뷰 내용에서 겹치는 부분이 많아서 재밌었어요.
글에서 어색한 부분을 수정해봤어요.

2024-07-04 12:27 UTC, alstn113 commented on interview/2024-05-22.md
> +    - 그것에 이름을 붙인 것이 방법론이다.
이런 느낌은 어떨까요?
```suggestion
    - 방법론이 먼저가 아니라 팀에 어떤 문제가 있었고, 그것을 해결하기 위해 떠올린 방법들 중에 이름을 붙인 것이 방법론이다.
```

2024-07-04 12:27 UTC, alstn113 commented on interview/2024-05-22.md
> +    - 능동적인 사람이어야 한다.
망쵸가 정리해준 슬랙을 봤는데 "평소에 문화에 관심이 많은 사람이어야 하나?" 이 부분이 어떤 맥락에서 나온건지 잘 기억이 안나네요.
그리고 "그냥 단순하게 질문할 수 있어야 한다"는 위에 내용과 겹치는 것 같아서 지우는게 좋을 것 같아요.

```suggestion
- 익명 코치가 생각하시는 신입에게 기대하는 역량
    - 크게 기대하는 건 없다. 면접을 통과했으니 기술적인 역량을 갖췄을 것을 기대한다.
    - 문화적인 걸로 무언가를 기대하지 않고, 아무렇지 않게 관성적으로 하고 있던 것에 의문을 갖는 것을 기대한다.
    - 이때 편하고 예쁘게 이야기할 수 있는 것을 기대한다. ex) 이건 왜 이렇게 하고 있는 거에요.
    - 능동적인 사람이어야 한다.
```

2024-07-04 12:54 UTC, 3Juhwan approved these changes
선뜻 정리해 주셔서 감사합니다. 아톰은 항상 저에게 좋은 동기부여가 돼요 😀 

한가지 제안입니다. 
- "익명"도 괜찮지만 읽다보니 어색하게 느껴졌어요
- `A 코치`, `ㅇㅇ 코치` 등은 어떤가요? 가볍게 제안해 봅니다. 
- 위처럼 하면 다음 인터뷰 정리는 `B 코치` 혹은 `ㅁㅁ코치`로 기록할 수 있을 것 같아요.

2024-07-04 12:54 UTC, 3Juhwan commented on interview/2024-05-22.md
> +    - 그것에 이름을 붙인 것이 방법론이다.
이 부분 구름이 먼저 언급해 주셨네요 :) 
제 제안은 다음과 같습니다. 한 줄로 줄이는 것에 초점을 둔 수정이고 편하게 채택해 주세요! 

```suggestion
    - 방법론이 먼저 생겨난 것이 아니다. 팀에 어떤 문제가 있었고 해결한 방법에 이름을 붙인 것이 방법론이다.
```

2024-07-05 00:27 UTC, le2sky commented on interview/2024-05-22.md
> +    - 그것에 이름을 붙인 것이 방법론이다.
내용이 더 눈에 잘보이는 것 같아요. 제안 감사합니다!

2024-07-05 00:27 UTC, le2sky commented on interview/2024-05-22.md
> +    - 능동적인 사람이어야 한다.
👍👍 굳굳 좋아요.

2024-07-05 00:44 UTC, le2sky commented on interview/2024-05-22.md
> +    - 그것에 이름을 붙인 것이 방법론이다.
굳굳 좋아요. 이 부분 반영했습니다! 
추가로 제안주신 것처럼 익명 코치 대신에 `ㅁㅁ`으로 변경해볼게요.

2024-07-05 09:47 UTC, alstn113 approved these changes

2024-07-05 11:41 UTC, GIVEN53 reviewed
정리 잘해주셨네요 👍🏻 항상 감사합니다 PR 헤더도 정말 좋아요
첫 인터뷰했던 시간이 다시 떠올라서 재미있네요

2024-07-05 11:41 UTC, GIVEN53 commented on interview/2024-05-22.md
> +    - 이때 편하게 예쁘게 이야기할 수 있는 것을 기대한다. ex) 이건 왜 이렇게 하고 있는 거에요.
```suggestion
    - 편하게, 예쁘게 이야기할 수 있는 것을 기대한다. ex) 어떤 이유때문에 이렇게 하셨는지 궁금해요!
```
'이 때'가 어느 때를 의미하는 건지 컨텍스트가 잘 이해되지 않아서 빼는 것도 좋을 것 같아요!
그리고 예시가 조금 딱딱해 보여서 수정해보았습니다

2024-07-05 11:41 UTC, GIVEN53 commented on interview/2024-05-22.md
> +    - 문화적인 걸로 무언가를 기대하지 않고, 아무렇지 않게 관성적으로 하고 있던 것에 의문을 갖는 것을 기대한다.
```suggestion
    - 문화적인 것에 대해서는 무언가를 기대하지 않는다. 하지만 아무렇지 않게 관성적으로 하고 있던 것에 의문을 가지길 기대한다.
```
이런 느낌은 어떨까요?

2024-07-05 11:41 UTC, GIVEN53 commented on interview/2024-05-22.md
> +    - 무엇을 말하고 있는지 바로 캐치할 수 있는지 중요하다.
```suggestion
    - 말하고자 하는 바를 상대방이 바로 캐치할 수 있도록 전달하는 것이 중요하다.
```
-지, -지의 반복이 어색하게 느껴져서 위와 같이 제안드립니다

2024-07-05 11:41 UTC, GIVEN53 commented on interview/2024-05-22.md
> +    - 이야기하면서 관심 분야와 일하고 싶은 것 공유하면서 만들어 나갈 수 있다.
```suggestion
    - 관심 분야와 일하고 싶은 것 등을 공유하면서 만들어 나갈 수 있다.
```
어색한 부분을 수정했고 편하게 채택해주세요!

2024-07-05 11:41 UTC, GIVEN53 commented on interview/2024-05-22.md
> +    - 처음 서로 다른 사람들이 만나서, 매일 각자의 생각이 변하는데 매일매일 다른 사람들이 만나는데 처음부터 정할 수 있을까?
```suggestion
    - 서로 다른 사람들이 처음 만났고, 각자의 생각도 매일 변하는데 과연 처음부터 정할 수 있을까?
```
'매일 매일 다른 사람들이 만난다'를 어떤 의미로 말씀해주셨는지 기억이 잘 안나네요
이해가 잘 안돼서 빼고 다듬어봤어요
어떤 의미였는지 기억나시면 코멘트 부탁드립니다

2024-07-05 11:41 UTC, GIVEN53 commented on interview/2024-05-22.md
> +    - 꼬리 답변) 버그가 있는지, 장애가 발생할 가능성이 있는지, 인프라 구조에 따라 트랜잭션이나 API 설계 등에 대한 고려한다.
```suggestion
    - 꼬리 답변) 버그가 있는지, 장애가 발생할 가능성이 있는지, 인프라 구조에 따라 트랜잭션이나 API 설계 등에 대해 고려한다.
```
어색한 부분을 수정했고 편하게 채택해주세요!

2024-07-06 05:30 UTC, 3Juhwan commented on interview/2024-05-22.md
> +    - 이때 편하게 예쁘게 이야기할 수 있는 것을 기대한다. ex) 이건 왜 이렇게 하고 있는 거에요.
```suggestion
    - 편하게, 예쁘게 이야기할 수 있는 것을 기대한다. ex) 어떤 이유 때문에 이렇게 하셨는지 궁금해요!
```

프린의 좋은 코멘트 남겨주셨는데 사소한 오타가 있어서 언급 해둡니다!

2024-07-06 05:31 UTC, 3Juhwan approved these changes
수정 사항이 좀 많았을 것 같아요. 고생하셨습니다!

2024-07-06 06:59 UTC, le2sky commented on interview/2024-05-22.md
> +    - 처음 서로 다른 사람들이 만나서, 매일 각자의 생각이 변하는데 매일매일 다른 사람들이 만나는데 처음부터 정할 수 있을까?
좋은 것 같아요! 매일 매일 다른 사람들이 왜 만나는지 기억은 나지 않네요. 
해당 문장에 핵심 메시지는 충분히 드러나는 것 같아서, 제안 주신대로 반영할게요!
감사합니다. 👍

2024-07-06 07:00 UTC, merged