[코치와의 인터뷰 2회차] 인터뷰 면담 일지 제출합니다.
2024-woowacourse-study/gae-mun-tam pull request #7
Opened 2024-07-06 06:56 UTC by 3Juhwan

안녕하세요, 망쵸입니다~
코치와의 인터뷰 2번째 일지 작성했습니다. 정리하면서 쭉 다시 읽어 보았는데, 그때의 기억이 나서 참 좋았어요. 
확인해 보고 수정이 필요하거나 의견 있으면 편하게 남겨주세요 :)

브랜치명을 모르겠어서 임의대로 `interview-2`로 했는데, 의견 부탁드려요!

2024-07-07 02:42 UTC, alstn113 approved these changes
인터뷰 내용이 잘 담겨있어서 좋았어요.
저는 사실 글의 문법이나 구조에 대해서 크게 신경쓰지 않아서 바로 approve 합니다.

마지막 개문탐 방향성에 대한 의견을 보면서 생각을 조금 했어요.
07/06에 했던 회의처럼 가볍게 얘기하는 것도 좋지만 확실한 목표를 세워야 할까가 고민이네요.

2024-07-07 04:16 UTC, 3Juhwan commented
구름의 의견에 동의해요! 어제 회의 내용이 훌륭했고 넘 좋은 경험이었어요. 그래도 좀더 명확한 목표가 있으면 좋을 것 같아요. 그 활동을 통해 의미 있는 결과물이 나오면 더 좋을 것 같아요! 
자세한 논의는 다른 곳에서 진행해 보면 좋을 것 같습니다아~

2024-07-07 11:07 UTC, GIVEN53 approved these changes
잘 정리해주셔서 감사합니다 망쵸 👍🏻 브랜치명은 자유롭게 해도 괜찮아 보입니다!

구름, 망쵸 의견처럼 다음 활동에서는 목표 설정을 중점으로 얘기해보면 좋을 것 같아요
크게 수정할 내용이 없어서 approve 드려요 고생 많으셨습니다

2024-07-07 11:07 UTC, GIVEN53 commented on interview/2024-06-12.md
> +- 갈등의 원인 파악 방법
인터뷰 당시 이 부분이 가장 인상 깊었었는데 다시 읽으니까 또 새롭네요 😌

2024-07-08 02:03 UTC, le2sky requested changes
늦어서 죄송합니다. 🥲
읽으면서 그때 기억이 다시 생각나네요. 따봉 백만개입니다. 👍
작은 피드백 하나 남겼습니다. 시간 나실 때 확인 부탁드립니다.

2024-07-08 02:03 UTC, le2sky commented on interview/2024-06-12.md
> +    - 코치로서 좋은 경험은 아니었다.
이 질문은 제가 했던 걸로 기억하는데요. 
돌이켜보면 좋은 질문은 아니었다고 생각해요. 따라서 좋은 답변을 기대하기 어려웠었어요. 
개인적으로 지워도 좋을 거 같은데 망쵸의 의견은 어떠신가요?

2024-07-08 10:39 UTC, 3Juhwan commented on interview/2024-06-12.md
> +    - 코치로서 좋은 경험은 아니었다.
발견해 주셔서 다행입니다. 감사합니다.

2024-07-08 10:59 UTC, le2sky approved these changes
오늘 하루도 고생 많으셨습니다! 이만 approve할게요.
더 추가하실 내용이 있다면 자유롭게 추가해주시고 아니라면 머지 부탁드려요. 👍

2024-07-08 11:07 UTC, merged