[5회차] 동아리 활동 일지 제출합니다.
2024-woowacourse-study/gae-mun-tam pull request #8
Opened 2024-07-08 11:22 UTC by alstn113

7월 6일 토요일에 진행한 5회차 동아리 일지를 제출합니다.
팀 프로젝트 과정에 대해 공유한 내용을 정리해봤습니다.

2시간 정도 분량이기도 했고, 클로바 노트를 처음 사용해서 오히려 더 힘들었던 것 같아요.

중간중간에 너무 개인적인 내용( ex) PR )은 주제와 거리가 먼 것 같아서 뺐습니다.
피드백 주시면 바로바로 더하고 제거하겠습니다

이번 주도 파이팅입니다!

2024-07-08 12:26 UTC, le2sky requested changes
구름! 활동 일지 잘 작성해주셨네요. 감사합니다. 👍
사소한 피드백 남겨놨어요. 시간 나실 때 편하게 확인 부탁드립니다.

2024-07-08 12:26 UTC, le2sky commented on log/2024-07-06.md
> +      - 팀이 말을 열심히 하고 시끄럽지 않다.
제가 생각을 제대로 표현하지 못했었네요. 😂
전하고 싶었던 바는 아래와 같아요. 

```suggestion
      - 말 하지 않는 사람들이 없고, 서로의 의견을 경청해준다.
```

2024-07-08 12:26 UTC, le2sky commented on log/2024-07-06.md
> +  - 코드 리뷰 방식(Pn 룰과 RCA 룰)**
뒤에 `**`은 없어도 좋을 것 같아요.

2024-07-08 12:26 UTC, le2sky commented on log/2024-07-06.md
> +#### 주제: 팀 프로젝트 과정 공유
스터디 진행 헤더는 없어도 괜찮겠네요.
다음과 같은 느낌은 어떨까요?

```suggestion
### 팀 프로젝트 과정 공유
```

2024-07-08 12:50 UTC, alstn113 commented on log/2024-07-06.md
> +#### 주제: 팀 프로젝트 과정 공유
헤더가 하나라서 좋은 것 같아요!

2024-07-08 14:37 UTC, GIVEN53 requested changes
내용이 많았을 텐데 잘 정리해 주셔서 감사합니다 👍🏻 
한 가지 수정사항이 있어서 편하실 때 확인하시고 반영 부탁드려요!

2024-07-08 14:37 UTC, GIVEN53 commented on log/2024-07-06.md
> +      - 개인마다 능력치가 달라서 진행자와 서기를 고정해 효율적인 회의를 한다.
해당 내용은 다른 주제에서 얘기했던 내용이라서 아래의 내용으로 변경해주시면 감사하겠습니다!
> 비정기 회의를 개최할 경우 개최자가 회의 시작 최소 1시간 전 희의 의사를 전달한다. 또한 회의 아젠다 및 회의 시간 설정, 마지막에 회의 내용을 요약해서 컨텍스트를 최종 공유한다.

2024-07-08 14:41 UTC, alstn113 commented on log/2024-07-06.md
> +      - 개인마다 능력치가 달라서 진행자와 서기를 고정해 효율적인 회의를 한다.
```suggestion
      - 비정기 회의를 개최할 경우 개최자가 회의 시작 최소 1시간 전 희의 의사를 전달한다. 또한 회의 아젠다 및 회의 시간 설정, 마지막에 회의 내용을 요약해서 컨텍스트를 최종 공유한다.
```

2024-07-08 16:55 UTC, GIVEN53 approved these changes
빠른 반영 👍🏻 👍🏻 
approve 하겠습니다 고생 많으셨어요 :)

2024-07-09 00:37 UTC, le2sky approved these changes
👍👍 고생 많으셨어요. approve 드릴게요.
필요한 부분이 있다고 판단되시면 자유롭게 추가 부탁드려요.

2024-07-09 11:20 UTC, 3Juhwan requested changes
조금 늦었죠..? 😅 이번 내용 엄청 많았는데 고생하셨습니다. 
바로 approve하고 싶었지만 맞춤법만 한 번 체크했어요. 최소한으로 지켜야 하는 사항이라고 생각해서요! 수정하고 알려주시면 바로 approve 하겠습니다.

2024-07-09 11:20 UTC, 3Juhwan commented on log/2024-07-06.md
> +      - 말 하지 않는 사람들이 없고, 서로의 의견을 경청해준다.
```suggestion
      - 말하지 않는 사람들이 없고, 서로의 의견을 경청해 준다.
```

2024-07-09 11:20 UTC, 3Juhwan commented on log/2024-07-06.md
> +      - 이해가 안되는 부분에 대해서 거리낌없이 말할 수 있고, 다른 팀원들이 개의치 않고 친절하게 설명해준다. 회의가 너무 깊거나 딴 방향으로 갈 때, 이를 지적하고 바로잡는 분위기가 형성되어 있다. 회의 주제와 결론을 명확히 정하고, 결론히 나지 않는 경우 다음 액션 플랜을 세워 회의 구조가 효율적이다.
```suggestion
      - 이해가 안 되는 부분에 대해서 거리낌 없이 말할 수 있고, 다른 팀원들이 개의치 않고 친절하게 설명해 준다. 회의가 너무 깊거나 딴 방향으로 갈 때, 이를 지적하고 바로잡는 분위기가 형성되어 있다. 회의 주제와 결론을 명확히 정하고, 결론이 나지 않는 경우 다음 액션 플랜을 세워 회의 구조가 효율적이다.
```

2024-07-09 11:20 UTC, 3Juhwan commented on log/2024-07-06.md
> +      - 비정기 회의를 개최할 경우 개최자가 회의 시작 최소 1시간 전 희의 의사를 전달한다. 또한 회의 아젠다 및 회의 시간 설정, 마지막에 회의 내용을 요약해서 컨텍스트를 최종 공유한다.
```suggestion
      - 비정기 회의를 개최할 경우 개최자가 회의 시작 최소 1시간 전 회의 의사를 전달한다. 또한 회의 아젠다 및 회의 시간 설정, 마지막에 회의 내용을 요약해서 컨텍스트를 최종 공유한다.
```

2024-07-09 11:20 UTC, 3Juhwan commented on log/2024-07-06.md
> +      - 결론이 안나는 논쟁을 할 때 시간을 정해두고 그 때까지 결론이 나지 않으면 다른 크루를 찾아가서 이름이 적힌 카드들을 주고 뽑은 카드에 적힌 사람을 따른다.
```suggestion
      - 결론이 안 나는 논쟁을 할 때 시간을 정해두고 그때까지 결론이 나지 않으면 다른 크루를 찾아가서 이름이 적힌 카드들을 주고 뽑은 카드에 적힌 사람을 따른다.
```

2024-07-09 11:20 UTC, 3Juhwan commented on log/2024-07-06.md
> +  - 프린: 기술과 사용자 두마리 토끼를 잡고 싶다. 프로젝트에서 적어도 하나의 기술은 배우고 싶다.
```suggestion
  - 프린: 기술과 사용자 두 마리 토끼를 잡고 싶다. 프로젝트에서 적어도 하나의 기술은 배우고 싶다.
```

2024-07-09 11:28 UTC, alstn113 commented on log/2024-07-06.md
> +      - 말 하지 않는 사람들이 없고, 서로의 의견을 경청해준다.
어우 맞춤법이 엉망이네요. 반성합니다. 수정하겠습니다,,,

2024-07-09 11:32 UTC, 3Juhwan approved these changes
마무리까지 고생하셨습니다 :)

2024-07-09 11:33 UTC, merged